using System.Net;
using ArangoDBNetStandard.Models;
using JetBrains.Annotations;
using Newtonsoft.Json;

namespace ArangoDBNetStandard.GraphApi.Models
{
    public class PostVertexResponse<T> : ResponseBase
    {
        /// <summary>
        /// The complete newly written vertex document. 
        /// Includes all written attributes in the request 
        /// body and all internal attributes generated by ArangoDB. 
        /// Will only be present if 
        /// <see cref="PostVertexOptions.ReturnNew"/> is true.
        /// </summary>
        public  T New { get; }

        public PostVertexResult Vertex { get; }

        [JsonConstructor]
        public PostVertexResponse(bool error, HttpStatusCode code, T @new, PostVertexResult vertex) : base(new ApiResponse(error, code))
        {
            New = @new;
            Vertex = vertex;
        }

        public PostVertexResponse([NotNull] ApiResponse responseDetails) : base(responseDetails)
        {
        }
    }
}
