using System.Net;
using ArangoDBNetStandard.Models;
using JetBrains.Annotations;
using Newtonsoft.Json;

namespace ArangoDBNetStandard.GraphApi.Models
{
    /// <summary>
    /// Represents a response containing information about the created edge in a graph.
    /// </summary>
    public class PostEdgeResponse<T> : ResponseBase
    {
        /// <summary>
        /// The internal attributes for the edge.
        /// </summary>
        public EdgeResult Edge { get; }

        /// <summary>
        /// The complete newly written edge document.
        /// Includes all written attributes in <see cref="T"/> and all internal attributes generated by ArangoDB.
        /// Will only be present if <see cref="PostEdgeQuery.ReturnNew"/> is true.
        /// </summary>
        public T New { get; }

        public PostEdgeResponse([NotNull] ApiResponse responseDetails) : base(responseDetails)
        {
        }

        [JsonConstructor]
        public PostEdgeResponse(bool error, HttpStatusCode code, EdgeResult edge, T @new) : base(new ApiResponse(error, code))
        {
            Edge = edge;
            New = @new;
        }
    }
}
